# Generated by Django 4.1.1 on 2022-09-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Baby",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_confirmed", models.BooleanField(default=False)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("rating", models.PositiveIntegerField()),
                ("image", models.ImageField(upload_to="uploads/babies/")),
                ("telegram_id", models.CharField(max_length=20)),
            ],
            options={"db_table": "baby",},
        ),
    ]
