export const donatersData = [
  { firstName: 'Данії ', surName: 'Стаднік', sum: 2 },
  { firstName: 'Павло ', surName: 'Пуха', sum: 30 + 0.66 + 5 + 0.23 },
  { firstName: 'Іван ', surName: 'Михалик', sum: 14 },
  { firstName: 'Роман ', surName: 'Ціпан', sum: 5 },
  { firstName: 'Вадим ', surName: 'Миткалик', sum: 15 + 14.88 },
  { firstName: 'Едуард ', surName: 'Костюкевич', sum: 0.45 },
  { firstName: 'Дмитро ', surName: 'Ярошик', sum: 9 },
  { firstName: 'Богдан ', surName: 'Павлік', sum: 6 },
  { firstName: 'Богдан ', surName: 'Стрилюк', sum: 1.94 },
  { firstName: 'Руслан  ', surName: 'Хільковець	', sum: 5 },
  { firstName: 'Іван ', surName: 'Токарець', sum: 20 },
  { firstName: 'Яна  ', surName: 'Міщеня', sum: 2 },
  { firstName: 'Артем ', surName: 'Віднік		', sum: 50 },
  { firstName: 'Станіслав ', surName: 'Тарасюк	', sum: 1 },
  { firstName: 'Андрій   ', surName: 'Денисюк		', sum: 69.69 },
  { firstName: 'Тетяна   ', surName: 'Ковтонюк		', sum: 150 },
  { firstName: 'Дмитро   ', surName: 'Будько			', sum: 100 + 100 },
  { firstName: 'Вадим    ', surName: 'Александрович 			', sum: 7.6 },
  { firstName: 'Вадим   ', surName: 'Гіль 			', sum: 30 },
  { firstName: 'Михайло    ', surName: 'Вершигора				', sum: 8 },
  { firstName: 'Роман', surName: 'Лапюк', sum: 10 },
  { firstName: 'Олександр ', surName: 'Демчук	', sum: 10 },
  { firstName: 'Дмитро ', surName: 'Нестюк		', sum: 500 + 279.95 },
  { firstName: 'Киця', surName: '', sum: 374 },
  { firstName: 'Артем ', surName: 'Головницький	', sum: 48 },
  { firstName: 'Юля ', surName: 'Хітько			', sum: 200 },
  { firstName: 'Андрій ', surName: 'Богдан ', sum: 32.96 },
  { firstName: 'Діана ', surName: 'Шелест ', sum: 20 },
  { firstName: 'Богдан ', surName: 'Стрилюк		', sum: 125 },
  { firstName: 'Сергій	', surName: 'Лісковчук ', sum: 20 },
  { firstName: 'Штик ', surName: 'Олександр		', sum: 26 },
  { firstName: 'Олександр	', surName: 'Кравчук ', sum: 50 },
  { firstName: 'Анонім ', surName: '1', sum: 310 },
  { firstName: 'Анонім ', surName: '2', sum: 15.53 },
  { firstName: 'Анонім ', surName: '3', sum: 25 },
];
